### ISSUE TITLE
omnipay/paypal gateways support mutlple gateways

### ISSUE THREAD

**Issue by sprklinginfo** [overtrue/laravel-payment#13]
from the [package github](https://github.com/thephpleague/omnipay-paypal), it says:
The following gateways are provided by this package:

PayPal_Express (PayPal Express Checkout)
PayPal_ExpressInContext (PayPal Express In-Context Checkout)
PayPal_Pro (PayPal Website Payments Pro)
PayPal_Rest (Paypal Rest API)

So in the _payments.php_ how do I add multiple gateways from this same package? 

May I do like this:

 'gateways' => [
        'PayPal_Express' => [
            'driver' => 'PayPal_Express',
            'options' => [
                'username' => env('PAYPAL_EXPRESS_USERNAME'),
                'password' => env('PAYPAL_EXPRESS_PASSWORD'),
                'signature' => env('PAYPAL_EXPRESS_SIGNATURE'),
                'test_mode' => env('PAYPAL_EXPRESS_TEST_MODE'),
            ],
        ],
 'PayPal_Rest' => [
            'driver' => 'PayPal_Rest',
            'options' => [
                'client_id' => env('PAYPAL_REST_USERNAME'),
                'client_secret' => env('PAYPAL_REST_PASSWORD'),
         
            ],
        ],
]

**Comment by overtrue** [comment]
yes
