### ISSUE TITLE
执行composer require overtrue/laravel-payment -v 提示package没找到

### ISSUE THREAD

**Issue by shubiao-yao** [overtrue/laravel-payment#2]
在我的项目中执行 composer require overtrue/laravel-payment -v

提示如下错误：
[InvalidArgumentException]                                                                                           
  Could not find package overtrue/laravel-payment at any version for your minimum-stability (stable). Check the packa  
  ge spelling or your minimum-stability 
我的laravel版本是5.5

**Comment by overtrue** [comment]
已经发版了，请过一会儿重试，使用国内源可能需要多等一会儿

**Comment by shubiao-yao** [comment]
好的
