### ISSUE TITLE
发布路径问题

### ISSUE THREAD

**Issue by ollbao** [overtrue/laravel-payment#5]
因为我们项目外面有两层目录(项目名称/code/框架代码),所以在 php artisan vendor:publis 的时候会报 Can't locate path: <0> 这个错误.
希望能将
`$this->publishes([
            __DIR__.'/../config/payments.php',
        ], 'config');`
改成
`$this->publishes([
            __DIR__.'/../config/payments.php' => config_path('payments.php'),
        ], 'config');`

**Comment by overtrue** [comment]
提 PR
